AWSTemplateFormatVersion: 2010-09-09
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: aws-network-basis-cfn
  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: ap-northeast-1d
      Tags:
        - Key: Name
          Value: aws-network-basis-cfn-public
      VpcId: !Ref VPC
  PrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ap-northeast-1d
      Tags:
        - Key: Name
          Value: aws-network-basis-cfn-private
      VpcId: !Ref VPC
# DBSubnet
  DBSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: ap-northeast-1a
      Tags:
        - Key: Name
          Value: aws-network-basis-cfn-db1
      VpcId: !Ref VPC
  DBSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: ap-northeast-1c
      Tags:
        - Key: Name
          Value: aws-network-basis-cfn-db2
      VpcId: !Ref VPC
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: aws-network-basis-cfn-gateway
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: aws-network-basis-cfn-public-route
  AddInternetGatewayToPublicRouteTable:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
  AttachPublicRouteTableToPublicSubnet:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet
Outputs:
  PublicSubnet:
    Value: !Ref PublicSubnet
    Export:
      Name: 'aws-network-basis:PublicSubnet'
  DBSubnet1:
    Value: !Ref DBSubnet1
    Export:
      Name: 'aws-network-basis:DBSubnet1'
  DBSubnet2:
    Value: !Ref DBSubnet2
    Export:
      Name: 'aws-network-basis:DBSubnet2'
  VPC:
    Value: !Ref VPC
    Export:
      Name: 'aws-network-basis:VPC'
